apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: default
spec:
  type: NodePort
  selector:
    app: todo-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008
